# Generated by Django 5.1.6 on 2025-03-18 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ingresos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingreso',
            old_name='categoria',
            new_name='tratamiento',
        ),
    ]
