# Generated by Django 5.1.6 on 2025-03-18 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ingresos', '0002_rename_categoria_ingreso_tratamiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tratamiento',
            options={'verbose_name': 'tratamiento', 'verbose_name_plural': 'tratamientos'},
        ),
    ]
