# Generated by Django 5.1.6 on 2025-03-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingresos', '0003_alter_tratamiento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='cliente',
            field=models.CharField(max_length=200),
        ),
    ]
