# Generated by Django 5.1.6 on 2025-03-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingresos', '0004_alter_ingreso_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='concepto',
            field=models.CharField(max_length=250),
        ),
    ]
