# Generated by Django 5.1.6 on 2025-03-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingresos', '0005_alter_ingreso_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='abono',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
